### ISSUE TITLE
Team Status "joining" does in a specific case not update the Date joined Correctly.

### ISSUE THREAD

**Issue by Me9a** [ENSL/ensl.org#111]
If you open a Teams Member management Page for example: https://www.ensl.org/teams/866/edit Members.

If a Player of a Team  gets set from status "Member, Depute, Leader" to status "joining" hes not showing up in the Member-list if you now set him back to the Status "Member, Depute, Leader" he has its old (first) "Date Joined" instead of the current Day.

SO Solutions are:
A) Leader/Depute/Admins should not be able to set People to the Status "joining" in a Team.
(or)
B) The Simple but not so pretty solution is to just have the Date in Joined when he Player actually changed last into the status of "Member, Depute, Leader"

Why this is a Problem:
1) A team could just put a carry into the status "joining" to get seeded for example into div3 instead of div2 cause they get seeded based on the 6 Strongest players and hes not visible in the Member-list that  can screw over the Seeding and then stomps might happen.

2) Cause there are rules that Players are blocked based on the Joined Date on the following cases: 
(g) Rosters will be locked and changes are no longer permitted, one (1) week before the conclusion of the regular season for each respective division.
(e) After the season begins, a player who joins or switches teams will be ineligible to play for that team as a member for seven (7) days. That player is eligible to play as a substitute.

**Comment by Absurdon** [comment]
fixed
