### ISSUE TITLE
Cant edit Any Contest (link error)

### ISSUE THREAD

**Issue by Me9a** [ENSL/ensl.org#91]
IT always comes to this error message: http://imgur.com/a/lLZyE
The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved.

Jiriki says its a link Problem and with an issue it can be fixed.

We need to be able to edit contests otherwise no s11....

**Comment by Absurdon** [comment]
Fixed for now. Was an issue with article categories. Error happened when trying to render the selection for the rules in edit.html.erb
