### ISSUE TITLE
Contact Page could need an Update

### ISSUE THREAD

**Issue by Me9a** [ENSL/ensl.org#94]
Contact Page should have these information on it in the TEXT:

> In case the contact form doesn't work write us on Steam 
> (add the people from here): http://www.ensl.org/about/staff.
> 
> If you have anything that can be Publicly visible contact us here:
> on Discord: https://discord.gg/tHte2pS
> 
> or in the Forum: http://www.ensl.org/forums

**Comment by Absurdon** [comment]
Done
